name: Build Widgets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-widgets:
    runs-on: ubuntu-latest

    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      R_LIBS_USER: /home/runner/work/_temp/Library
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # Or a more recent version like '4.x' or 'latest'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            pandoc \
            build-essential

      - name: Install R dependencies
        run: |
          # The r-lib/actions/setup-r@v2 action usually configures R to use
          # the RSPM env var if set. Let's make sure it's used.
          R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'tidyr', 'plotly', 'htmlwidgets', 'here'), repos=Sys.getenv('RSPM'))"

      - name: Run R script to generate widgets
        run: Rscript Afikseis_Touristwn.R

      - name: Run R script
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs Logs_Afikseis_Touristwn
          git commit -m "Generate HTML widgets for GitHub Pages" || echo "No changes to commit"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs' # Upload the 'docs' folder where widgets are saved

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
