name: Build Widgets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-widgets:
    runs-on: ubuntu-latest

    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      R_LIBS_USER: /home/runner/work/_temp/Library
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          Rscript -e 'remotes::install_cran(c("httr", "jsonlite", "dplyr", "tidyr", "plotly", "htmlwidgets", "here"), dependencies = TRUE)'

      - name: Run R script
        run: |
          Rscript Afikseis_Touristwn.R
