name: Generate R Widgets and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R dependencies
        run:
          R -e "install.packages(c('httr', 'jsonlite', 'dplyr', 'tidyr', 'plotly', 'htmlwidgets', 'here'), repos='https://cloud.r-project.org')"

      - name: Run R script to generate widgets
        run: Rscript Afikseis_Touristwn.R

      - name: Configure Git for Deployment
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs backups
          git commit -m "Generate HTML widgets for GitHub Pages" || echo "No changes to commit"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs' # Upload the 'docs' folder where widgets are saved

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
